##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## Makefile
##

all:	$(NAME)

clean:
	make -C part1/step1 clean
	make -C part1/step2 clean
	make -C part1/step3 clean
	make -C part1/step4 clean
	make -C part1/step5 clean

fclean:
	make -C part1/step1 fclean
	make -C part1/step2 fclean
	make -C part1/step3 fclean
	make -C part1/step4 fclean
	make -C part1/step5 fclean

re:
	make -C part1/step1 re
	make -C part1/step2 re
	make -C part1/step3 re
	make -C part1/step4 re
	make -C part1/step5 re
