jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            assignments:
              - "chocolateen"
            permissions:
              - "Overall/Administer"
          - name: "ape"
            description: "Pedagogical team member"
            assignments:
              - "i_dont_know"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            assignments:
              - "vaugie_g"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Configure"
              - "Job/Move"
              - "Job/Cancel"
          - name: "assist"
            description: "Assistant"
            assignments:
              - "nasso"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"

# jobs:
  # - script: >
  #     folder('/Tools') {
  #       displayName('Tools')
  #       description('Folder for miscellaneous tools.')
  #     }

  #     freeStyleJob('/Tools/CLONE-REPOSITORY') {
  #       wrappers {
  #         preBuildCleanup()
  #       }
  #       parameters {
  #         stringParam("GIT_REPOSITORY_URL", "", "Git URL of the repository to clone")
  #       }
  #       steps {
  #         shell("git clone ${GIT_REPOSITORY_URL}")
  #       }
  #     }

  #     freeStyleJob('/Tools/SEED') {
  #       wrappers {
  #         preBuildCleanup()
  #       }
  #       parameters {
  #         stringParam("GITHUB_NAME", "", 'GitHub repository owner/repo_name (e.g.: \"EpitechIT31000/chocolatine\")')
  #         stringParam("DISPLAY_NAME", "", "Display name for the job”")
  #       }
  #       steps {
  #           dsl {
  #             filename('job_dsl.groovy')
  #             additionalParams([
  #               'githubName': "${GITHUB_NAME}",
  #               'displayName': "${DISPLAY_NAME}"
  #             ])
  #           }
  #         }
  #     }

jobs:
  - file: ./job_dsl.groovy
