---
- name: Create directory for poll application
  ansible.builtin.file:
    path: /etc/poll
    state: directory
    mode: '0755'

- name: Extract poll application archive
  become: true
  ansible.builtin.unarchive:
    src: poll.tar
    dest: /etc/poll
    owner: root
    group: root
    mode: '0755'

- name: Install python3-pip package
  become: true
  ansible.builtin.package:
    name:
      - python3-pip
    state: present

- name: Install poll application python requirements
  become: true
  ansible.builtin.pip:
    requirements: /etc/poll/requirements.txt

- name: Template poll application systemd service
  ansible.builtin.template:
    src: poll.j2
    dest: /etc/systemd/system/poll.service
    mode: '0644'
  register: template_poll

- name: Reload systemd configuration
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    name: poll
  when: template_poll.changed

- name: Enable poll application service at boot
  become: true
  ansible.builtin.systemd:
    enabled: yes
    name: poll.service

- name: Start poll application service
  become: true
  ansible.builtin.service:
    name: poll.service
    state: started

- name: Restart poll application service
  become: true
  ansible.builtin.service:
    name: poll.service
    state: restarted
  when: template_poll.changed
