version: '3'

services:

  db:
    image: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
      - back-tier
    restart: on-failure

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure

  poll:
    build: poll/
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: on-failure
    depends_on:
      - redis

  worker:
    build: worker/
    networks:
      - back-tier
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: on-failure
    depends_on:
      - db
      - redis

  result:
    build: result/
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: on-failure
    depends_on:
      - db

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier:
