all:
	make -C PLANE
	make -C SPHERE
	make -C CYLINDER

clean:
	make clean -C PLANE
	make clean -C SPHERE
	make clean -C CYLINDER

fclean:
	make fclean -C PLANE
	make fclean -C SPHERE
	make fclean -C CYLINDER

re:	fclean all
