##
## EPITECH PROJECT, 2021
## project
## File description:
## Makefile
##

all:
	cp zappy_ai.py ../zappy_ai

clean:
	rm -r -f __pycache__

fclean:	clean
	rm -f ../zappy_ai

re:	clean all


.PHONY:		all clean fclean re
