##
## EPITECH PROJECT, 2022
## B-CCP-400-MLH-4-1-theplazza-thomas.ott
## File description:
## Makefile
##

all:
	make -C Plazza

clean:
	make clean -C Plazza

fclean:
	make fclean -C Plazza

re:	fclean all
