##
## EPITECH PROJECT, 2021
## makefile
## File description:
## makefile
##

all:
	make -C SNAKE
	make -C NIBBLER

clean:
	make clean -C SNAKE
	make clean -C NIBBLER

fclean:
	make fclean -C SNAKE
	make fclean -C NIBBLER

re:	fclean all