name: chocolatine

on:
  pull_request:
  push:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2026/B-DOP-200-MLH-2-1-chocolatine-thomas.ott.git'
  EXECUTABLES: 'a.out'

jobs:
  check_program_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run date
        run: date

  check_program_compilation:
    needs: check_program_cleanliness
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run make
        run: make
        timeout-minutes: 2
      - name: make clean
        run: make clean

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run make tests_run
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{env.MIRROR_URL}}
          ssh_private_key:
            ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}